services:
  crc-alerts-service:
    build:
      context: .
    environment:
      NODE_ENV: production

  crc-alerts-db:
    image: timescale/timescaledb:latest-pg15
    container_name: alerts-postgres
    restart: always
    volumes:
      - crc-alerts-volume:/home/postgres/pgdata/data
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_PORT=${DB_PORT}
      - POSTGRES_DATABASE=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

networks:
  default:
    name: crc-network
    external: true

volumes:
  crc-alerts-volume:
    name: crc-alerts-volume
